import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { IBM_Plex_Mono } from "next/font/google";
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ibm-plex-mono", // <-- use a unique, descriptive variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={ibmPlexMono.variable}>
      <body className="bg-neutral-900 text-white font-ibm">
        <Navbar />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}



